// <auto-generated />
namespace Altkom._09_11._12._2019.CSharp.Basics.Db.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111413161_AddPerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
